CREATE TABLE IF NOT EXISTS user (
	userId INT IDENTITY(1, 1) PRIMARY KEY,
	userName VARCHAR(50) NOT NULL,
	email VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(200) NOT NULL,
	role VARCHAR(50) NOT NULL,
	permission BOOLEAN NOT NULL,
	frozen BOOLEAN NOT NULL,
	requestedAt VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS reissuePassword (
	reissuePasswordId INT IDENTITY(1, 1) PRIMARY KEY,
	userId INT NOT NULL,
	passwordResetToken VARCHAR(50) NOT NULL,
	expirationTime TIMESTAMP NOT NULL,
	changed BOOLEAN NOT NULL
);


CREATE TABLE IF NOT EXISTS contract (
	contractId INT IDENTITY(1, 1) PRIMARY KEY,
	contractTime INT NOT NULL,
	startTime TIME NOT NULL,
	breakTime TIME NOT NULL,
	endTime TIME NOT NULL,
	startDate DATE NOT NULL,
	officeName VARCHAR(100) NOT NULL,
	endDate DATE,
	userId INT NOT NULL
);


CREATE TABLE IF NOT EXISTS month (
 	monthId INT IDENTITY(1, 1) PRIMARY KEY,
 	year INT NOT NULL,
 	month INT NOT NULL,
 	deadlineStatus BOOLEAN NOT NULL,
 	requestStatus BOOLEAN NOT NULL,
 	contractId INT NOT NULL
 );


CREATE TABLE IF NOT EXISTS workTime (
	workTimeId INT IDENTITY(1, 1) PRIMARY KEY,
	workDay DATE NOT NULL,
	startTime TIMESTAMP NOT NULL,
	breakTime TIME NOT NULL,
	endTime TIMESTAMP NOT NULL,
	workTimeMinute INT NOT NULL,
	contractId INT NOT NULL,
	monthId INT NOT NULL
);